# Generated by Django 3.0.6 on 2020-05-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcuser", "0004_fcuser_useremial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fcuser", old_name="useremial", new_name="useremail",
        ),
    ]
