name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Install black
        run: pip install black 

      - name: Linting with black
        run: python -m balck .
