name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1

      - name: Lint with black
        run: python -m black .
